// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyvlvnuupagaumaacgyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5dmx2bnV1cGFnYXVtYWFjZ3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzY1NzIsImV4cCI6MjA2NzYxMjU3Mn0.ovZXw3yFidM-gtxHPay__Aw2_CbNbfB7yh6o-h5LP_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});